name: Build and Release Go Executable

on:
  push:
    branches:
      - "release/*"
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  release:
    name: Create Release
    runs-on: ubuntu-latest
    needs: build
    permissions: write-all
    outputs:
      timestamp: ${{ steps.get-timestamp.outputs.time }}
    steps:
      - name: Get build timestamp
        id: get-timestamp
        run: |
          echo "time=$(/bin/date -u "+%Y-%m-%d-%H%M")" >> $GITHUB_OUTPUT
      - name: Generate environmental variables
        id: generate_env_vars
        run: |
          echo "tag_name=release_${{ steps.get-timestamp.outputs.time }}" >> $GITHUB_OUTPUT
          echo "release_name=GameOfLife_build_${{ steps.get-timestamp.outputs.time }}" >> $GITHUB_OUTPUT
      - run: |
          gh release create ${{ steps.generate_env_vars.outputs.tag_name }} \
            ./bin/* \
            --prerelease \
            --title "${{ steps.generate_env_vars.outputs.release_name }}" \
            --target "$(git log -1 --format='%H')"
            --notes "Automated release"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build:
    name: Build binaries and create release
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-go@v6
        with:
          go-version: ">=1.22"
      - run: "go version"
      - name: install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install make
          sudo apt-get install libgl1-mesa-dev libxi-dev libxcursor-dev libxrandr-dev libxinerama-dev libwayland-dev libxkbcommon-dev
          go install
      - name: Build
        run: |
          make build
          ls ./bin

